### ISSUE TITLE
Database connection framework

### ISSUE THREAD

**Issue by ielizaga** [pivotal-gss/gpmt2#8]
Create an db connection framework to be used in most tools that need access to the Greenplum database.

**Comment by ielizaga** [comment]
I believe #5 is a WIP for this issue.

**Comment by ielizaga** [comment]
@Tylarb @faisaltheparttimecoder Are we certain that we want to place our utilities in the cmd package instead of main or a utils package?

**Comment by tylarb** [comment]
@ielizaga  I'm starting on ssh today - we'll move them to a utils package. I'll make that change as part of my PR(s)

**Comment by faisaltheparttimecoder** [comment]
Moved them to the utils folder @Tylarb if that commits looks good you can work on from there.
